export const descriptions = {
  cadMerenda:
    "O CadMerenda foi o primeiro projeto de grande porte que eu participei. Foi também o primeiro sistema robusto desenvolvido pelo setor de TI da Secretaria de Educação do Estado de Alagoas. Na jornada, participei de diversas reuniões com stakeholders, prototipei interfaces, desenvolvi o front-end e integrei com o back-end. Também auxiliei com o deploy da aplicação e a manutenção do sistema.\n\nFoi um projeto desafiador, visto que tive que aprender React durante o desenvolvimento, mas consegui aprender em um ritmo acelerado e no fim das contas, deu tudo certo. Foi uma aplicação desenvolvida quase que exclusivamente por estagiários.",
  gap: "Este foi o segundo projeto que desenvolvi na secretaria. A fim de organizar os diversos projetos que o CadMerenda inspirou, desenvolvemos o GAP. O sistema foi desenvolvido para a Superintendência de Infraestrutura e Tecnologia da SEDUC para gerenciar ações e projetos da secretaria. No período entre o CadMereda e o GAP, foquei em aperfeiçoar minhas habilidades, e, participando do projeto, me vi em uma posição quase como senior, auxiliando os estagiários e tendo que resolver os problemas mais desafiadores.",
  oxeBanking:
    "Projeto de um banco digital fictício, desenvolvido para a matéria Conceitos de Linguagens de Programação do curso de Ciência da Computação na Universidade Federal de Alagoas (UFAL).\n\nComo parte da ementa da matéria, os alunos devem implementar um sistema de internet banking com várias tecnologias diferentes. O projeto foi desenvolvido em um período de 3 meses. Era um projeto de grande porte, com muitas funcionalidades e uma interface complexa. Assim, foi facilmente um dos mais desafiadores que participei pelo prazo e porque tive que aprender a trabalhar com Svelte em um curto período de tempo. Éramos apenas dois devs para desenvolver e prototipar.",
  avalies:
    "O Avalies está nos estágios iniciais de desenvolvimento. É uma aplicação para avaliação de Instituições de Ensino Superior (IES) de Alagoas. O projeto está sendo desenvolvido pela Secretaria de Educação do Estado de Alagoas, com o objetivo de facilitar todo o processo que hoje é feito através de planilhas e documentos físicos.\n\nEste projeto está sendo feito no modelo MVC, utilizando Laravel para o back-end e React para o front-end. Neste projeto, uma nova experiência que estou tendo é a de atuar como tech lead e product manager, auxiliando a equipe de desenvolvimento e fazendo a ponte entre os stakeholders e a equipe de desenvolvimento. Sou responsável por designar tarefas, auxiliar no desenvolvimento e garantir que o projeto esteja dentro do escopo e prazo. Além disso, continuo com as atividades padrão de desenvolvimento fullstack: modelagem do banco, elaboração de controllers, prototipação, configuração de repositório e afins.\n\nEste é o primeiro projeto que estou liderando do começo ao fim.",
  obito:
    "Esta aplicação estática foi desenvolvida para o trabalho de conclusão de curso de uma mestranda. Um professor recrutou uma equipe para que pudesse desenvolver o mais rápido possível uma aplicação que digitaliza o processo de registro de óbitos em Alagoas. O projeto foi desenvolvido em React, com deploy no Vercel. Ele conta com uma funcionalidade de gerar um PDF com os dados do óbito, com regras de negócio específicas para que as informações sejam consistentes. O projeto foi desenvolvido em um período de 1 mês e meio.",
  bumy: "Bumy é o meu primeiro contrato como freelancer. Dentro do projeto, fui responsável pela prototipação e desenvolvimento integral da aplicação, sendo a única pessoa no front-end. Participei de reuniões semanais, onde apresentava o progresso do projeto e discutia com o cliente as próximas etapas. O projeto está na reta final, apenas no estágio de elminação de bugs e ajustes finais e já conta com um ambiente de homologação.",
  lighthouse:
    "Atualmente participo da equipe da Lighthouse Software Systems, que desenvolve um sistema de gestão de provedores de internet em parceria com uma empresa. O sistema é desenvolvido em React e Laravel, e conta com uma equipe de 4 desenvolvedores. Devido a confidencialidade do projeto, não posso fornecer muitos detalhes, mas posso dizer que é um projeto de grande porte, com muitas funcionalidades e desafios técnicos.",
  andarilho:
    "Andarilho é um projeto de denúncias de acessibilidade desenvolvido para a disciplina de Projeto de Software do curso de Ciência da Computação da Universidade Federal de Alagoas (UFAL). O projeto foi desenvolvido em React, com deploy no Vercel, em um período de 3 meses, com uma equipe de 5 desenvolvedores.\n\nÉ possível ver a landing page e a tela de login no link abaixo, mas a API não está no ar devido a custos de hospedagem.",
};
