import { descriptions } from "./descriptions";

import avalies from "@/images/Avalies/cover.png";
import bumy from "@/images/Bumy/cover.png";
import lighthouse from "@/images/Lighthouse/cover.png";
import cadMerenda from "@/images/Misc/cadMerenda.png";
import gap from "@/images/Misc/gap.png";
import obito from "@/images/Misc/obito.png";
import oxeBanking from "@/images/Oxebanking/cover.png";
import { Work } from "@/types";

export const works: Work[] = [
  {
    id: "7",
    title: "Bumy",
    subtitle: "Geração de conteúdos automatizada.",
    description: descriptions.bumy,
    technologies: ["React", "TailwindCSS", "TypeScript"],
    roles: ["UI/UX Designer, Desenvolvedor Front-End"],
    workPlace: "Freelance",
    when: "2025",
    status: "completed",
    cover: bumy,
    images: [
      "https://raw.githubusercontent.com/Ashlc/portfolio/refs/heads/main/src/images/Bumy/briefing.png",
      "https://raw.githubusercontent.com/Ashlc/portfolio/refs/heads/main/src/images/Bumy/checkout.png",
      "https://raw.githubusercontent.com/Ashlc/portfolio/refs/heads/main/src/images/Bumy/orders.png",
      "https://raw.githubusercontent.com/Ashlc/portfolio/refs/heads/main/src/images/Bumy/plan.png",
      "https://raw.githubusercontent.com/Ashlc/portfolio/refs/heads/main/src/images/Bumy/post.png",
      "https://raw.githubusercontent.com/Ashlc/portfolio/refs/heads/main/src/images/Bumy/schedules.png",
      "https://raw.githubusercontent.com/Ashlc/portfolio/refs/heads/main/src/images/Bumy/support.png",
      "https://raw.githubusercontent.com/Ashlc/portfolio/refs/heads/main/src/images/Bumy/trend.png",
    ],
  },
  {
    id: "3",
    title: "Oxebanking",
    subtitle: "Trabalho da matéria de CLP",
    description: descriptions.oxeBanking,
    technologies: ["Svelte", "TailwindCSS", "JavaScript"],
    roles: ["Desenvolvedor Front-End", "UI/UX Designer"],
    workPlace: "UFAL",
    repo: "https://github.com/Ashlc/oxebanking",
    when: "2024",
    status: "completed",
    cover: oxeBanking,
    images: [
      "https://raw.githubusercontent.com/Ashlc/portfolio/refs/heads/main/src/images/Oxebanking/imagem_2025-01-23_113923390.png",
      "https://raw.githubusercontent.com/Ashlc/portfolio/refs/heads/main/src/images/Oxebanking/imagem_2025-01-23_113942363.png",
      "https://raw.githubusercontent.com/Ashlc/portfolio/refs/heads/main/src/images/Oxebanking/imagem_2025-01-23_114026984.png",
      "https://raw.githubusercontent.com/Ashlc/portfolio/refs/heads/main/src/images/Oxebanking/imagem_2025-01-23_114100382.png",
    ],
  },
  {
    id: "8",
    title: "Lighthouse",
    subtitle: "PJ de desenvolvimento de software",
    description: descriptions.lighthouse,
    roles: ["Desenvolvedor Full-stack, UI/UX Designer, DevOps"],
    technologies: ["React", "Laravel", "TailwindCSS", "TypeScript", "PHP"],
    workPlace: "Freelance",
    when: "2025",
    status: "completed",
    cover: lighthouse,
    images: [
      "https://raw.githubusercontent.com/Ashlc/portfolio/refs/heads/main/src/images/Lighthouse/audit.png",
      "https://raw.githubusercontent.com/Ashlc/portfolio/refs/heads/main/src/images/Lighthouse/modules.png",
      "https://raw.githubusercontent.com/Ashlc/portfolio/refs/heads/main/src/images/Lighthouse/home.png",
    ],
    link: "https://lhs.digital/",
  },
  {
    id: "1",
    title: "CadMerenda",
    subtitle: "Gerenciamento de cardápios escolares",
    technologies: [
      "React",
      "TailwindCSS",
      "JavaScript",
      "Express.js",
      "MySQL",
      "Docker",
    ],
    description: descriptions.cadMerenda,
    roles: ["Desenvolvedor Front-End", "UI/UX Designer"],
    workPlace: "SEDUC",
    when: "2023-2024",
    status: "completed",
    cover: cadMerenda,
    link: "https://cadmerenda.educacao.al.gov.br",
  },
  {
    id: "2",
    title: "GAP - Gestão de Ações e Projetos",
    subtitle: "Sistema de organização de projetos",
    technologies: ["React", "TypeScript", "TailwindCSS"],
    description: descriptions.gap,
    roles: ["Desenvolvedor Front-End"],
    workPlace: "SEDUC",
    when: "2024",
    status: "completed",
    cover: gap,
    link: "https://gap.educacao.al.gov.br",
  },
  {
    id: "4",
    title: "Avalies",
    subtitle: "Avaliação online de IES",
    technologies: ["React", "Laravel", "TailwindCSS", "JavaScript", "PHP"],
    description: descriptions.avalies,
    roles: [
      "Desenvolvedor Fullstack",
      "UI/UX Designer",
      "Product Manager",
      "Tech Lead",
    ],
    workPlace: "SEDUC",
    when: "2025",
    status: "ongoing",
    cover: avalies,
    images: [
      "https://raw.githubusercontent.com/Ashlc/portfolio/refs/heads/main/src/images/Avalies/imagem_2025-01-23_114515127.png",
      "https://raw.githubusercontent.com/Ashlc/portfolio/refs/heads/main/src/images/Avalies/imagem_2025-01-23_114209839.png",
      "https://raw.githubusercontent.com/Ashlc/portfolio/refs/heads/main/src/images/Avalies/imagem_2025-01-23_114540998.png",
      "https://raw.githubusercontent.com/Ashlc/portfolio/refs/heads/main/src/images/Avalies/imagem_2025-01-23_114551595.png",
    ],
  },
  {
    id: "6",
    title: "D.O. Eletrônico",
    subtitle: "Geração de D.O para o Hospital Universiário",
    description: descriptions.obito,
    technologies: ["React", "TypeScript", "TailwindCSS"],
    roles: ["Desenvolvedor Front-End"],
    workPlace: "SEDUC",
    when: "2025",
    status: "completed",
    link: "https://obito-chi.vercel.app/",
    cover: obito,
  },
];
